apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
        - name: spark-master
          image: bitnami/spark:latest
          command: [ "/bin/bash", "-c", "/opt/bitnami/spark/sbin/start-master.sh && tail -f /dev/null" ]
          ports:
            - containerPort: 8080
            - containerPort: 7077